// <auto-generated />
using CarListApp.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListApp.Api.Migrations
{
    [DbContext(typeof(CarListDbContext))]
    [Migration("20230227093527_inital")]
    partial class inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("CarListApp.Api.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "HONDA",
                            Model = "Civic",
                            Vin = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Make = "TATA",
                            Model = "Neon",
                            Vin = "2345"
                        },
                        new
                        {
                            Id = 3,
                            Make = "BMW",
                            Model = "A6",
                            Vin = "5678"
                        },
                        new
                        {
                            Id = 4,
                            Make = "MAHINDRA",
                            Model = "THAR",
                            Vin = "0987"
                        },
                        new
                        {
                            Id = 5,
                            Make = "TOYOTA",
                            Model = "Fortuner",
                            Vin = "6542"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
